<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" language="java" %>
<%@ include file="/WEB-INF/JSPF/inmo_db-conexion.jspf" %>
<%@ page import="java.sql.*" %>
<%@ page import="java.nio.file.*" %>
<%@ page import="javax.servlet.http.Part" %>
<%if(session.getAttribute("usuarioId")==null){response.sendRedirect("../login.jsp?error=acceso");return;}String tituloPagina="Subir documento | Inmoraiz";String id=request.getParameter("id_solicitud");String mensaje=request.getParameter("mensaje");if("POST".equalsIgnoreCase(request.getMethod())){try{Part archivo=request.getPart("archivo");if(archivo==null||archivo.getSize()==0)throw new IllegalArgumentException();String original=Paths.get(archivo.getSubmittedFileName()).getFileName().toString();String extension=original.contains(".")?original.substring(original.lastIndexOf('.')).toLowerCase():"";if(!( ".pdf".equals(extension)||".jpg".equals(extension)||".jpeg".equals(extension)||".png".equals(extension)))throw new IllegalArgumentException();String seguro="solicitud-"+id+"-"+System.currentTimeMillis()+extension;Path carpeta=Paths.get(application.getRealPath("/uploads/documentos"));Files.createDirectories(carpeta);archivo.write(carpeta.resolve(seguro).toString());String ruta=request.getContextPath()+"/uploads/documentos/"+seguro;Class.forName("com.mysql.cj.jdbc.Driver");try(Connection c=abrirConexion();PreparedStatement p=c.prepareStatement("INSERT INTO documento_solicitud(id_solicitud,nombre_archivo,ruta_archivo,tipo_documento) SELECT s.id_solicitud,?,?,? FROM solicitud s WHERE s.id_solicitud=? AND s.id_cliente=?")){p.setString(1,original);p.setString(2,ruta);p.setString(3,request.getParameter("tipo_documento"));p.setInt(4,Integer.parseInt(id));p.setInt(5,(Integer)session.getAttribute("usuarioId"));if(p.executeUpdate()==0)throw new SecurityException("Solicitud no pertenece al usuario");}response.sendRedirect("documentos.jsp?id_solicitud="+id);return;}catch(Exception e){mensaje="error";}}%>
<!DOCTYPE html><html lang="es"><head><%@include file="/WEB-INF/JSPF/inmo_head.jspf"%></head><body><%@include file="/WEB-INF/JSPF/inmo_navbar.jspf"%><main class="container py-5"><div class="row justify-content-center"><div class="col-lg-7"><div class="card border-0 shadow-sm p-4"><h1 class="h3 fw-bold">Subir documento</h1><p class="text-muted">PDF, JPG o PNG hasta 5 MB.</p><%if("error".equals(mensaje)){%><div class="alert alert-danger">No fue posible guardar el documento.</div><%}%><form method="post" enctype="multipart/form-data"><input type="hidden" name="id_solicitud" value="<%=id%>"><label class="form-label">Tipo de documento</label><input class="form-control mb-3" name="tipo_documento" placeholder="Cédula, ingresos..." required><input class="form-control mb-4" type="file" name="archivo" accept="application/pdf,image/jpeg,image/png" required><button class="btn btn-primary">Subir documento</button></form></div></div></div></main><%@include file="/WEB-INF/JSPF/inmo_footer.jspf"%></body></html>


